[global]
template_dir = "templates"

[global.databases.postgres_database]
url = "postgres://christiandrappi@localhost:5432/rcv"

[production]
address = "127.0.0.1"
port = 8000
workers = 1
keep_alive = 5
log = "critical"
secret_key = "/qC88ypjiIzpjGqnubQK5HOW7UN1DBO/hJMP60FnOb8="
limits = { forms = 8192 }
